// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTools(arg1) {
  return window['go']['main']['App']['CheckTools'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function GetOutputFolder() {
  return window['go']['main']['App']['GetOutputFolder']();
}

export function GetToolPaths() {
  return window['go']['main']['App']['GetToolPaths']();
}

export function InstallFfmpeg() {
  return window['go']['main']['App']['InstallFfmpeg']();
}

export function InstallYtdlp() {
  return window['go']['main']['App']['InstallYtdlp']();
}
