// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetToolPaths() {
  return window['go']['main']['App']['GetToolPaths']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallFfmpeg() {
  return window['go']['main']['App']['InstallFfmpeg']();
}
