// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';
import {main} from '../models';

export function CheckTools(arg1:boolean):Promise<tools.ToolPaths>;

export function Download(arg1:main.DownloadOptions):Promise<string>;

export function GetOutputFolder():Promise<string>;

export function GetToolPaths():Promise<tools.ToolPaths>;

export function Greet(arg1:string):Promise<string>;

export function InstallFfmpeg():Promise<string>;
