// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {tools} from '../models';

export function Download(arg1:main.DownloadOptions):Promise<string>;

export function GetDebugInfo():Promise<main.DebugInfo>;

export function GetOutputFolder():Promise<string>;

export function GetSensibleDownloadFolder():Promise<string>;

export function GetToolPaths():Promise<tools.ToolPaths>;

export function GetUpdateInfo():Promise<main.UpdateInfo>;

export function InstallDeno():Promise<string>;

export function InstallFfmpeg():Promise<string>;

export function InstallYtdlp():Promise<string>;
