// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetOutputFolder() {
  return window['go']['main']['App']['GetOutputFolder']();
}

export function GetSensibleDownloadFolder() {
  return window['go']['main']['App']['GetSensibleDownloadFolder']();
}

export function GetToolPaths() {
  return window['go']['main']['App']['GetToolPaths']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function InstallDeno() {
  return window['go']['main']['App']['InstallDeno']();
}

export function InstallFfmpeg() {
  return window['go']['main']['App']['InstallFfmpeg']();
}

export function InstallYtdlp() {
  return window['go']['main']['App']['InstallYtdlp']();
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
