name: Wails Build

on:
  push:
    # tags:
    #   - "v*" # Triggers on tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        # Define the target OS and the corresponding runner
        include:
          - os: windows-latest
            platform: windows/amd64
            artifact_name: hoshino-downloader-windows-amd64
          - os: macos-latest
            platform: darwin/universal # Universal binary for Intel and Apple Silicon
            artifact_name: hoshino-downloader-macos
          - os: ubuntu-latest
            platform: linux/amd64
            artifact_name: hoshino-downloader-linux-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.4" # Update this to match your go.mod

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install UPX
        if: runner.os != 'MacOS'
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      # Linux requires specific WebKit and GTK dependencies to compile
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev build-essential pkg-config

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Application on Linux
        if: runner.os == 'Linux'
        run: wails build -tags webkit2_41 -upx -platform ${{ matrix.platform }}

      - name: Build Application
        if: runner.os != 'Linux'
        run: wails build -upx -platform ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/bin/
          retention-days: 7
          archive: false
